---
- hosts: all

  vars:
    chemin_racine: "{{ ansible_env.HOME }}"
    chemin_client: "{{ chemin_racine }}/client"
    chemin_serveur: "{{ chemin_racine }}/serveur"
    chemin_orchestrateur: "{{ chemin_racine }}/orchestrateur"
    chemin_config: "{{ ansible_env.HOME }}/config"
    version_orchestrateur: master
    version_serveur: master
    version_client: master
    hote_client: app.eva.beta.gouv.fr
    hote_serveur: api.app.eva.beta.gouv.fr
    docker_compose_environnement:
      CHEMIN_CLIENT: "{{ chemin_client }}"
      CHEMIN_SERVEUR: "{{ chemin_serveur }}"
      HOTE_CLIENT: "{{ hote_client }}"
      HOTE_SERVEUR: "{{ hote_serveur }}"
      RESEAU_TRAEFIK: "traefik"
      COMPOSE_PROJECT_NAME: "{{ chemin_racine|replace('/', '-') }}"

  tasks:
    - name: Clone ou met à jour le dépot
      git:
        repo: "https://github.com/betagouv/{{ item.depot }}.git"
        version: "{{ item.version }}"
        dest: "{{ item.destination }}"
        force: yes
      loop:
        - destination: "{{ chemin_orchestrateur }}"
          depot: eva-orchestrateur
          version: "{{ version_orchestrateur }}"

        - destination: "{{ chemin_serveur }}"
          depot: eva-serveur
          version: "{{ version_serveur }}"

        - destination: "{{ chemin_client }}"
          depot: eva
          version: "{{ version_client }}"

    - name: Copie le fichier d'environnement de production vers l'orchestrateur
      copy:
        remote_src: yes
        src: "{{ chemin_config }}/.env.serveur.prod"
        dest: "{{ chemin_orchestrateur }}/.env.serveur.prod"

    - name: Construis les images docker
      command: docker-compose build --pull
      args:
        chdir: "{{ chemin_orchestrateur }}"
      environment: "{{ docker_compose_environnement }}"

    - name: sauvegarde la base avant deploiement
      command: docker-compose run --rm pgbackups /backup.sh
      args:
        chdir: "{{ chemin_orchestrateur }}"
      environment: "{{ docker_compose_environnement }}"

    - name: Lance les tâches de gestion de la base de données
      command: docker-compose run --rm serveur bundle exec rails db:migrate
      args:
        chdir: "{{ chemin_orchestrateur }}"
      environment: "{{ docker_compose_environnement }}"

    - name: Démarre les images
      command: docker-compose up -d
      args:
        chdir: "{{ chemin_orchestrateur }}"
      environment: "{{ docker_compose_environnement }}"
