version: "3"
services:

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "${PORT}:80"
      - "7700:7700"
    depends_on:
      - client
      - serveur

  client:
    image: node:10
    env_file:
      - .env.client
    working_dir: /app
    command: npm run dev
    depends_on:
      - serveur

  serveur:
    image: ruby:2.6
    env_file:
      - .env.serveur
    working_dir: /app
    command: bundle exec ./bin/rails server --binding 0.0.0.0
    depends_on:
      - postgres

  postgres:
    image: postgres:11
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  pgbackups:
    image: prodrigestivill/postgres-backup-local:11
    env_file:
      - .env.serveur
    volumes:
      - pgbackups:/backups
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_EXTRA_OPTS=-Z9 --blobs --format=c
      - SCHEDULE=@yearly
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=80

volumes:
  pgbackups:
