version: "2"
services:

  client:
    build:
      context: ${CHEMIN_CLIENT}
      args:
        URL_SERVEUR: "https://${HOTE_SERVEUR}"
        JETON_CLIENT_ROLLBAR: "e92a61f4d5f242afb40e0b4f8c3d3a4c"
    restart: always
    depends_on:
      - serveur
    networks:
      - "${RESEAU_TRAEFIK}"
    labels:
      traefik.enable: 'true'
      traefik.frontend.rule: 'Host: ${HOTE_CLIENT}'
      traefik.port: '80'
      traefik.docker.network: '${RESEAU_TRAEFIK}'

  serveur:
    build:
      context: ${CHEMIN_SERVEUR}
      args:
        RAILS_ENV: production
    environment:
      HOTE_SERVEUR: "${HOTE_SERVEUR}"
    env_file:
      - .env.serveur.prod
    restart: always
    depends_on:
      - postgres
    networks:
      - "${RESEAU_TRAEFIK}"
      - postgres
    labels:
      traefik.enable: 'true'
      traefik.frontend.rule: 'Host: ${HOTE_SERVEUR}'
      traefik.port: '3000'
      traefik.docker.network: '${RESEAU_TRAEFIK}'

  postgres:
    image: postgres:11
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres

volumes:
  pgdata:

networks:
  traefik:
    external: true
  postgres:
