version: "3"
services:

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "${PORT}:80"
    depends_on:
      - client
      - serveur

  client:
    image: node:10
    env_file:
      - .env.client
    working_dir: /app
    command: npm run dev
    depends_on:
      - serveur

  serveur:
    image: ruby:2.6
    env_file:
      - .env.serveur
    working_dir: /app
    command: bundle exec ./bin/rails server --binding 0.0.0.0
    depends_on:
      - postgres

  postgres:
    image: postgres:11
