#!/bin/sh

set -e

if [ -n "$DOCKER_SYNC" ]
then
  docker-sync start
fi

./script/docker-compose-dev run --rm client npm install
./script/docker-compose-dev run --rm serveur bundle install --path vendor
./script/docker-compose-dev run --rm serveur ./bin/rails db:create
./script/docker-compose-dev run --rm serveur ./bin/rails db:migrate RAILS_ENV=development
./script/docker-compose-dev up -d
