#!/bin/sh

COMPOSE_FILE=docker-compose-dev-base.yml
if [ $(uname) == "Darwin" ]
then
  COMPOSE_FILE=$COMPOSE_FILE:docker-compose-dev-mac.yml
else
  COMPOSE_FILE=$COMPOSE_FILE:docker-compose-dev-linux.yml
fi

export COMPOSE_FILE
docker-compose $@
